#!/bin/bash

# stahnout hlviskove soubory
apt-get update
apt-get install linux-headers-$(uname -r)

# zjisteni cislne rady jadra
name=$(uname -r)
ver=${name:0:3}
lin="linux-$ver"
echo $lin

# presun do adresre se stejnym jadrem jako ma prave bezici linux
cd ./$lin
pwd

# v dotycnem adresari pak spustiti doit
./doit

